export const MEDICAL_DISCLAIMER =
  "PsyScreening hanya untuk screening awal dan edukasi, bukan diagnosis medis atau psikologis profesional.";

export const SCREENING_QUESTION_SEED = [
  {
    id: "q_sleep_hours",
    key: "sleepHours",
    title: "Dalam 7 hari terakhir, rata-rata berapa jam Anda tidur setiap malam?",
    helperText: "Masukkan estimasi angka yang paling mendekati kondisi Anda.",
    inputType: "number",
    min: 0,
    max: 14,
    step: 0.5,
    placeholder: "Contoh: 6.5",
    required: true,
    order: 1,
  },
  {
    id: "q_sleep_quality",
    key: "sleepQuality",
    title: "Bagaimana kualitas tidur Anda belakangan ini?",
    helperText: "Pilih opsi yang paling menggambarkan kondisi Anda.",
    inputType: "choice",
    required: true,
    order: 2,
    options: [
      { label: "Nyenyak dan cukup konsisten", value: "baik" },
      { label: "Kadang terganggu", value: "cukup" },
      { label: "Sering terbangun / tidak nyenyak", value: "buruk" },
    ],
  },
  {
    id: "q_stress_level",
    key: "stressLevel",
    title: "Seberapa tinggi tingkat stres harian Anda saat ini?",
    helperText: "Geser dari 1 sangat rendah sampai 10 sangat tinggi.",
    inputType: "slider",
    min: 1,
    max: 10,
    step: 1,
    required: true,
    order: 3,
  },
  {
    id: "q_daily_activity",
    key: "activityLevel",
    title: "Bagaimana pola aktivitas harian Anda minggu ini?",
    helperText: "Perhatikan konsistensi rutinitas, energi, dan produktivitas.",
    inputType: "choice",
    required: true,
    order: 4,
    options: [
      { label: "Aktif dan relatif stabil", value: "tinggi" },
      { label: "Cukup aktif tetapi naik turun", value: "sedang" },
      { label: "Cenderung menurun / sulit konsisten", value: "rendah" },
    ],
  },
  {
    id: "q_mood",
    key: "moodState",
    title: "Bagaimana suasana hati Anda dalam beberapa hari terakhir?",
    helperText: "Pilih deskripsi yang paling sesuai.",
    inputType: "choice",
    required: true,
    order: 5,
    options: [
      { label: "Relatif stabil", value: "stabil" },
      { label: "Kadang mudah lelah / cemas", value: "berfluktuasi" },
      { label: "Sering sedih, kosong, atau tertekan", value: "menurun" },
    ],
  },
  {
    id: "q_social_support",
    key: "socialSupport",
    title: "Seberapa besar dukungan sosial yang Anda rasakan saat ini?",
    helperText: "Dukungan bisa dari keluarga, teman, pasangan, atau lingkungan kerja.",
    inputType: "choice",
    required: true,
    order: 6,
    options: [
      { label: "Saya merasa cukup didukung", value: "baik" },
      { label: "Ada dukungan, tetapi terbatas", value: "cukup" },
      { label: "Saya merasa cukup sendirian", value: "rendah" },
    ],
  },
  {
    id: "q_notes",
    key: "notes",
    title: "Apakah ada hal yang paling banyak memengaruhi kondisi mental Anda akhir-akhir ini?",
    helperText: "Opsional, isi bila Anda ingin memberi konteks tambahan.",
    inputType: "textarea",
    required: false,
    placeholder: "Tuliskan pemicu utama, kebiasaan, atau konteks pribadi Anda...",
    order: 7,
  },
];
